/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.pedro.dev.tarefa.model.impl;

import com.pedro.dev.tarefa.model.Tarefa;
import com.pedro.dev.tarefa.service.TarefaLocalServiceUtil;

/**
 * The extended model base implementation for the Tarefa service. Represents a row in the &quot;ToDoList_Tarefa&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TarefaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TarefaImpl
 * @see Tarefa
 * @generated
 */
public abstract class TarefaBaseImpl extends TarefaModelImpl implements Tarefa {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tarefa model instance should use the <code>Tarefa</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TarefaLocalServiceUtil.addTarefa(this);
		}
		else {
			TarefaLocalServiceUtil.updateTarefa(this);
		}
	}

}