/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.pedro.dev.tarefa.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.pedro.dev.tarefa.model.Tarefa;
import com.pedro.dev.tarefa.model.TarefaModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Tarefa service. Represents a row in the &quot;ToDoList_Tarefa&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TarefaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TarefaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TarefaImpl
 * @generated
 */
@JSON(strict = true)
public class TarefaModelImpl
	extends BaseModelImpl<Tarefa> implements TarefaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tarefa model instance should use the <code>Tarefa</code> interface instead.
	 */
	public static final String TABLE_NAME = "ToDoList_Tarefa";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"tarefaId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"titulo", Types.VARCHAR}, {"descricao", Types.VARCHAR},
		{"urlImagem", Types.VARCHAR}, {"status", Types.INTEGER},
		{"tarefaPaiId", Types.BIGINT}, {"fileEntryId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tarefaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("titulo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("descricao", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("urlImagem", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("tarefaPaiId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileEntryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ToDoList_Tarefa (uuid_ VARCHAR(75) null,tarefaId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,titulo VARCHAR(75) null,descricao VARCHAR(2000) null,urlImagem TEXT null,status INTEGER,tarefaPaiId LONG,fileEntryId LONG)";

	public static final String TABLE_SQL_DROP = "drop table ToDoList_Tarefa";

	public static final String ORDER_BY_JPQL = " ORDER BY tarefa.titulo ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ToDoList_Tarefa.titulo ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TAREFAPAIID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TITULO_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TarefaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _tarefaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTarefaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _tarefaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Tarefa.class;
	}

	@Override
	public String getModelClassName() {
		return Tarefa.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Tarefa, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Tarefa, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Tarefa, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Tarefa)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Tarefa, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Tarefa, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Tarefa)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Tarefa, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Tarefa, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Tarefa, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Tarefa, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Tarefa, Object>>();

			attributeGetterFunctions.put("uuid", Tarefa::getUuid);
			attributeGetterFunctions.put("tarefaId", Tarefa::getTarefaId);
			attributeGetterFunctions.put("groupId", Tarefa::getGroupId);
			attributeGetterFunctions.put("companyId", Tarefa::getCompanyId);
			attributeGetterFunctions.put("userId", Tarefa::getUserId);
			attributeGetterFunctions.put("userName", Tarefa::getUserName);
			attributeGetterFunctions.put("createDate", Tarefa::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Tarefa::getModifiedDate);
			attributeGetterFunctions.put("titulo", Tarefa::getTitulo);
			attributeGetterFunctions.put("descricao", Tarefa::getDescricao);
			attributeGetterFunctions.put("urlImagem", Tarefa::getUrlImagem);
			attributeGetterFunctions.put("status", Tarefa::getStatus);
			attributeGetterFunctions.put("tarefaPaiId", Tarefa::getTarefaPaiId);
			attributeGetterFunctions.put("fileEntryId", Tarefa::getFileEntryId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Tarefa, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Tarefa, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Tarefa, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Tarefa, String>)Tarefa::setUuid);
			attributeSetterBiConsumers.put(
				"tarefaId", (BiConsumer<Tarefa, Long>)Tarefa::setTarefaId);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Tarefa, Long>)Tarefa::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Tarefa, Long>)Tarefa::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Tarefa, Long>)Tarefa::setUserId);
			attributeSetterBiConsumers.put(
				"userName", (BiConsumer<Tarefa, String>)Tarefa::setUserName);
			attributeSetterBiConsumers.put(
				"createDate", (BiConsumer<Tarefa, Date>)Tarefa::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Tarefa, Date>)Tarefa::setModifiedDate);
			attributeSetterBiConsumers.put(
				"titulo", (BiConsumer<Tarefa, String>)Tarefa::setTitulo);
			attributeSetterBiConsumers.put(
				"descricao", (BiConsumer<Tarefa, String>)Tarefa::setDescricao);
			attributeSetterBiConsumers.put(
				"urlImagem", (BiConsumer<Tarefa, String>)Tarefa::setUrlImagem);
			attributeSetterBiConsumers.put(
				"status", (BiConsumer<Tarefa, Integer>)Tarefa::setStatus);
			attributeSetterBiConsumers.put(
				"tarefaPaiId",
				(BiConsumer<Tarefa, Long>)Tarefa::setTarefaPaiId);
			attributeSetterBiConsumers.put(
				"fileEntryId",
				(BiConsumer<Tarefa, Long>)Tarefa::setFileEntryId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getTarefaId() {
		return _tarefaId;
	}

	@Override
	public void setTarefaId(long tarefaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tarefaId = tarefaId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTitulo() {
		if (_titulo == null) {
			return "";
		}
		else {
			return _titulo;
		}
	}

	@Override
	public void setTitulo(String titulo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_titulo = titulo;
	}

	@JSON
	@Override
	public String getDescricao() {
		if (_descricao == null) {
			return "";
		}
		else {
			return _descricao;
		}
	}

	@Override
	public void setDescricao(String descricao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_descricao = descricao;
	}

	@JSON
	@Override
	public String getUrlImagem() {
		if (_urlImagem == null) {
			return "";
		}
		else {
			return _urlImagem;
		}
	}

	@Override
	public void setUrlImagem(String urlImagem) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_urlImagem = urlImagem;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public long getTarefaPaiId() {
		return _tarefaPaiId;
	}

	@Override
	public void setTarefaPaiId(long tarefaPaiId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tarefaPaiId = tarefaPaiId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTarefaPaiId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("tarefaPaiId"));
	}

	@JSON
	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileEntryId = fileEntryId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Tarefa.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Tarefa.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Tarefa toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Tarefa>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TarefaImpl tarefaImpl = new TarefaImpl();

		tarefaImpl.setUuid(getUuid());
		tarefaImpl.setTarefaId(getTarefaId());
		tarefaImpl.setGroupId(getGroupId());
		tarefaImpl.setCompanyId(getCompanyId());
		tarefaImpl.setUserId(getUserId());
		tarefaImpl.setUserName(getUserName());
		tarefaImpl.setCreateDate(getCreateDate());
		tarefaImpl.setModifiedDate(getModifiedDate());
		tarefaImpl.setTitulo(getTitulo());
		tarefaImpl.setDescricao(getDescricao());
		tarefaImpl.setUrlImagem(getUrlImagem());
		tarefaImpl.setStatus(getStatus());
		tarefaImpl.setTarefaPaiId(getTarefaPaiId());
		tarefaImpl.setFileEntryId(getFileEntryId());

		tarefaImpl.resetOriginalValues();

		return tarefaImpl;
	}

	@Override
	public Tarefa cloneWithOriginalValues() {
		TarefaImpl tarefaImpl = new TarefaImpl();

		tarefaImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		tarefaImpl.setTarefaId(this.<Long>getColumnOriginalValue("tarefaId"));
		tarefaImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		tarefaImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		tarefaImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		tarefaImpl.setUserName(this.<String>getColumnOriginalValue("userName"));
		tarefaImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		tarefaImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		tarefaImpl.setTitulo(this.<String>getColumnOriginalValue("titulo"));
		tarefaImpl.setDescricao(
			this.<String>getColumnOriginalValue("descricao"));
		tarefaImpl.setUrlImagem(
			this.<String>getColumnOriginalValue("urlImagem"));
		tarefaImpl.setStatus(this.<Integer>getColumnOriginalValue("status"));
		tarefaImpl.setTarefaPaiId(
			this.<Long>getColumnOriginalValue("tarefaPaiId"));
		tarefaImpl.setFileEntryId(
			this.<Long>getColumnOriginalValue("fileEntryId"));

		return tarefaImpl;
	}

	@Override
	public int compareTo(Tarefa tarefa) {
		int value = 0;

		value = getTitulo().compareTo(tarefa.getTitulo());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Tarefa)) {
			return false;
		}

		Tarefa tarefa = (Tarefa)object;

		long primaryKey = tarefa.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Tarefa> toCacheModel() {
		TarefaCacheModel tarefaCacheModel = new TarefaCacheModel();

		tarefaCacheModel.uuid = getUuid();

		String uuid = tarefaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			tarefaCacheModel.uuid = null;
		}

		tarefaCacheModel.tarefaId = getTarefaId();

		tarefaCacheModel.groupId = getGroupId();

		tarefaCacheModel.companyId = getCompanyId();

		tarefaCacheModel.userId = getUserId();

		tarefaCacheModel.userName = getUserName();

		String userName = tarefaCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			tarefaCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			tarefaCacheModel.createDate = createDate.getTime();
		}
		else {
			tarefaCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			tarefaCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			tarefaCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		tarefaCacheModel.titulo = getTitulo();

		String titulo = tarefaCacheModel.titulo;

		if ((titulo != null) && (titulo.length() == 0)) {
			tarefaCacheModel.titulo = null;
		}

		tarefaCacheModel.descricao = getDescricao();

		String descricao = tarefaCacheModel.descricao;

		if ((descricao != null) && (descricao.length() == 0)) {
			tarefaCacheModel.descricao = null;
		}

		tarefaCacheModel.urlImagem = getUrlImagem();

		String urlImagem = tarefaCacheModel.urlImagem;

		if ((urlImagem != null) && (urlImagem.length() == 0)) {
			tarefaCacheModel.urlImagem = null;
		}

		tarefaCacheModel.status = getStatus();

		tarefaCacheModel.tarefaPaiId = getTarefaPaiId();

		tarefaCacheModel.fileEntryId = getFileEntryId();

		return tarefaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Tarefa, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Tarefa, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Tarefa, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Tarefa)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Tarefa>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Tarefa.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _tarefaId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _titulo;
	private String _descricao;
	private String _urlImagem;
	private int _status;
	private long _tarefaPaiId;
	private long _fileEntryId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Tarefa, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Tarefa)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("tarefaId", _tarefaId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("titulo", _titulo);
		_columnOriginalValues.put("descricao", _descricao);
		_columnOriginalValues.put("urlImagem", _urlImagem);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("tarefaPaiId", _tarefaPaiId);
		_columnOriginalValues.put("fileEntryId", _fileEntryId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("tarefaId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("titulo", 256L);

		columnBitmasks.put("descricao", 512L);

		columnBitmasks.put("urlImagem", 1024L);

		columnBitmasks.put("status", 2048L);

		columnBitmasks.put("tarefaPaiId", 4096L);

		columnBitmasks.put("fileEntryId", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Tarefa _escapedModel;

}