version: '3.8'

services:
  liferay:
    image: liferay/portal:7.4.3.132-ga132
    container_name: liferay-portal
    ports:
      - "8080:8080"   # Mapeia a porta do container para a porta da máquina local
    environment:
      - LIFERAY_JVM_OPTS=-Duser.timezone=America/Sao_Paulo   # Definindo o fuso horário, se necessário
    volumes:
      - liferay_data:/opt/liferay/data  # Persistência de dados
      - ./deploy:/opt/liferay/deploy  # Mapeia a pasta 'deploy' local para o diretório 'deploy' do Liferay
    networks:
      - liferay-net

  database:
    image: mysql:5.7
    container_name: liferay-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: liferay
    ports:
      - "3306:3306"
    volumes:
      - liferay_db_data:/var/lib/mysql
    networks:
      - liferay-net

networks:
  liferay-net:
    driver: bridge

volumes:
  liferay_data:
  liferay_db_data:
